%YAML:1.0

# Minimum and maximum disparity
dMin: 0
dMax: 60

# Parameters for the cost-initialization for the ADCensus
censusWinH: 9
censusWinW: 7
defaultBorderCost: 0.999
lambdaAD: 10.0
lambdaCensus: 30.0

# The path where the results and intermediate results are stored.
savePath: "results/"

# Parameters for the cross-based cost aggregation
aggregatingIterations: 4
colorThreshold1: 20
colorThreshold2: 6
maxLength1: 34
maxLength2: 17

# Parameters for the optimization of image cells
colorDifference: 15
pi1: 0.1
pi2: 0.3

# Parameters for outlier detection
dispTolerance: 0

# Parameters for the iterative range rating
votingThreshold: 20
votingRatioThreshold: 0.4

# Parameters for the proper interpolation
maxSearchDepth: 20

# Parameters for the approximation of depths discontinuities 
cannyThreshold1: 20
cannyThreshold2: 60
cannyKernelSize: 3

# Parameters for the sub-pixel enhancement
blurKernelSize: 3



